iMaxwell = actxserver('AnsoftMaxwell.MaxwellScriptInterface')
Desktop = iMaxwell.GetAppDesktop()
Desktop.RestoreWindow

Project = Desktop.NewProject
invoke(Project,'InsertDesign','Maxwell 2D','Design1','Magnetostatic','')
Design = Project.SetActiveDesign('Design1')
invoke(Design,'SetSolutionType','Magnetostatic', 'about Z')

Editor = Design.SetActiveEditor('2D Modeler')

invoke(Editor,'CreateRectangle', ...
{'NAME:RectangleParameters', 'CoordinateSystemID:=',-1, ...
'IsCovered:=', true, 'XStart:=', '0mm', 'YStart:=', '0mm', 'ZStart:=', '0mm', ...
'Width:=', '2mm', 'Height:=', '2mm', 'WhichAxis:=', 'Y'}, ...
{'NAME:Attributes', 'Name:=', 'Rectangle1', 'Flags:=', '', ...
'Color:=', '{132 132 193}', 'Transparency:=', 0, 'PartCoordinateSystem:=',  ...
'Global', 'MaterialName:=', 'vacuum', 'SolveInside:=', true})
  
invoke(Design,'ChangeProperty', ...
{'NAME:AllTabs', {'NAME:LocalVariableTab', ...
{'NAME:PropServers', 'LocalVariables'}, {'NAME:NewProps', ...
{'NAME:D1', 'PropType:=', 'VariableProp', 'UserDef:=', true, ...
'Value:=', '2mm'}}}})
  
invoke(Design,'ChangeProperty', ...
{'NAME:AllTabs', {'NAME:LocalVariableTab', ...
{'NAME:PropServers', 'LocalVariables'}, {'NAME:NewProps', ...
{'NAME:H1', 'PropType:=', 'VariableProp', 'UserDef:=', ...
true, 'Value:=', '1mm'}}}})
  
invoke(Editor,'ChangeProperty' ,...
{'NAME:AllTabs', {'NAME:Geometry3DCmdTab', {'NAME:PropServers',...
'Rectangle1:CreateRectangle:1'}, {'NAME:ChangedProps', ...
{'NAME:XSize', 'Value:=', 'D1/2'}, {'NAME:ZSize', 'Value:=', 'H1'}}}})
  
invoke(Editor,'CreateRectangle' ,...
{'NAME:RectangleParameters', 'CoordinateSystemID:=', -1, ...
'IsCovered:=', true, ...
'XStart:=', '0.3mm', 'YStart:=', '0mm', 'ZStart:=', '0.2mm', ...
'Width:=', '0.6mm', 'Height:=', '0.8mm', 'WhichAxis:=', 'Y'}, ...
{'NAME:Attributes', 'Name:=', 'Rectangle2', 'Flags:=', '', ...
'Color:=', '{132 132 193}', 'Transparency:=', 0, 'PartCoordinateSystem:=', ...
'Global', 'MaterialName:=', 'vacuum', 'SolveInside:=', true})
  
invoke(Design,'ChangeProperty' ,...
{'NAME:AllTabs', {'NAME:LocalVariableTab', {'NAME:PropServers',...
'LocalVariables'}, {'NAME:NewProps', ...
{'NAME:H2', 'PropType:=', 'VariableProp', 'UserDef:=', ...
true, 'Value:=', '0.6mm'}}}})
  
invoke(Design,'ChangeProperty' ,...
{'NAME:AllTabs', {'NAME:LocalVariableTab', {'NAME:PropServers',...
'LocalVariables'}, {'NAME:NewProps', {'NAME:D2', ...
'PropType:=', 'VariableProp', 'UserDef:=', true, 'Value:=', '1mm'}}}})
  
invoke(Design,'ChangeProperty' ,...
{'NAME:AllTabs', ...
{'NAME:LocalVariableTab', {'NAME:PropServers', 'LocalVariables'}, ...
{'NAME:NewProps', {'NAME:extra', 'PropType:=', 'VariableProp', ...
'UserDef:=', true, 'Value:=', '0.1mm'}}}})

invoke(Editor,'ChangeProperty' ,...
{'NAME:AllTabs', ...
{'NAME:Geometry3DCmdTab', {'NAME:PropServers', ...
'Rectangle2:CreateRectangle:1'}, {'NAME:ChangedProps', ...
{'NAME:Position', 'X:=', 'D2/2', 'Y:=', '0mm', 'Z:=', '(H1-H2)/2'}, ...
{'NAME:XSize', 'Value:=', '(D1-D2)/2+extra'}, ...
{'NAME:ZSize', 'Value:=', 'H2'}}}})
  
invoke(Editor,'Subtract' ,...
{'NAME:Selections', 'Blank Parts:=', ...
'Rectangle1', 'Tool Parts:=', 'Rectangle2'}, ...
{'NAME:SubtractParameters', 'CoordinateSystemID:=', -1, ...
'KeepOriginals:=', false})
  
invoke(Editor,'CreateRectangle' ,...
{'NAME:RectangleParameters', ...
'CoordinateSystemID:=', -1, 'IsCovered:=', true, ...
'XStart:=', '0.5mm', 'YStart:=', '0mm', 'ZStart:=', '0.2mm', ...
'Width:=', '0.6mm', 'Height:=', '0.4mm', 'WhichAxis:=', 'Y'}, ...
{'NAME:Attributes', 'Name:=', 'Rectangle3', 'Flags:=', '', ...
'Color:=', '{132 132 193}', 'Transparency:=', 0, ...
'PartCoordinateSystem:=', 'Global', 'MaterialName:=', 'vacuum', ...
'SolveInside:=', true})
  
invoke(Design,'ChangeProperty', ...
{'NAME:AllTabs', ...
{'NAME:LocalVariableTab', {'NAME:PropServers', 'LocalVariables'}, ...
{'NAME:NewProps', {'NAME:ratio', 'PropType:=', ...
'VariableProp', 'UserDef:=', true, 'Value:=', '0.85'}}}})
  
invoke(Editor,'ChangeProperty' ,...
{'NAME:AllTabs', ...
{'NAME:Geometry3DCmdTab', {'NAME:PropServers', ...
'Rectangle3:CreateRectangle:1'}, {'NAME:ChangedProps', ...
{'NAME:Position', 'X:=', 'D2/2', 'Y:=', '0mm', 'Z:=', '(H1-H2)/2'}, ...
{'NAME:XSize', 'Value:=', '(D1-D2)/2*ratio'}, ...
{'NAME:ZSize', 'Value:=', 'H2'}}}})
  
invoke(Editor,'CreateRegion', ...
{'NAME:RegionParameters', ...
'CoordinateSystemID:=', -1, '+XPadding:=', '300', '-XPadding:=', '300', ...
'+YPadding:=', '0', '-YPadding:=', '0', ...
'+ZPadding:=', '300', '-ZPadding:=', '300'}, ...
{'NAME:Attributes', 'Name:=', 'Region', 'Flags:=', 'Wireframe#', ...
'Color:=', '{255 0 0}', 'Transparency:=', 0, 'PartCoordinateSystem:=', ...
'Global', 'MaterialName:=', 'vacuum', 'SolveInside:=', true})
  
Module = Design.GetModule('BoundarySetup')

invoke(Module,'AssignBalloon', ...
{'NAME:Balloon1', 'Edges:=', {57, 56, 55}})

invoke(Editor,'ChangeProperty', ...
{'NAME:AllTabs', ...
{'NAME:Geometry3DAttributeTab', {'NAME:PropServers', 'Rectangle1'}, ...
{'NAME:ChangedProps', {'NAME:Name', 'Value:=', 'core'}, ...
{'NAME:Material', 'Material:=', 'ferrite'}, ...
{'NAME:Color', 'R:=', 0, 'G:=', 0, 'B:=', 255}}}})
  
invoke(Editor,'ChangeProperty', ...
{'NAME:AllTabs', {'NAME:Geometry3DAttributeTab', ...
{'NAME:PropServers', 'Rectangle3'}, {'NAME:ChangedProps', ...
{'NAME:Name', 'Value:=', 'COIL'}, {'NAME:Material', 'Material:=', ...
'copper'}, {'NAME:Color', 'R:=', 255, 'G:=', 0, 'B:=', 0}}}})
  
invoke(Design,'ChangeProperty', ...
{'NAME:AllTabs', {'NAME:LocalVariableTab', {'NAME:PropServers',...
'LocalVariables'}, {'NAME:NewProps', ...
{'NAME:N', 'PropType:=', 'VariableProp', 'UserDef:=', true, ...
'Value:=', '10'}}}})
  
invoke(Design,'ChangeProperty', ...
{'NAME:AllTabs', {'NAME:LocalVariableTab', {'NAME:PropServers',...
'LocalVariables'}, {'NAME:NewProps', ...
{'NAME:Idc', 'PropType:=', 'VariableProp', 'UserDef:=', true, ...
'Value:=', '1A'}}}})
  
invoke(Module,'AssignCurrent', ...
{'NAME:Current1', 'Objects:=', {'COIL'}, 'Current:=', ...
'N*Idc', 'IsPositive:=', true})
  
Module = Design.GetModule('MaxwellParameterSetup')

invoke(Module,'AssignMatrix', ...
{'NAME:Matrix1', {'NAME:MatrixEntry', {'NAME:MatrixEntry', ...
'Source:=', 'Current1', 'NumberOfTurns:=', 'N', 'ReturnPath:=', 'infinite'}}, ...
{'NAME:MatrixGroup'}})
  
Module = Design.GetModule('AnalysisSetup')

invoke(Module,'InsertSetup', ...
'Magnetostatic', {'NAME:Setup1', 'MaximumPasses:=', 10, ...
'MinimumPasses:=', 2, 'MinimumConvergedPasses:=', 1, ...
'PercentRefinement:=', 30, 'SolveFieldOnly:=', false, ...
'PercentError:=', 1, 'SolveMatrixAtLast:=', true, ...
'UseOutputVariable:=', false, 'PreAdaptMesh:=', false, ...
'NonLinearResidual:=', 0.0001, 'MuNonLinearBH:=', true, ...
'ComputeHc:=', false, 'HcNonLinearBH:=', true})

Module = Design.GetModule('Optimetrics')

invoke(Module,'InsertSetup', ...
'OptiParametric', {'NAME:ParametricSetup1', ...
{'NAME:ProdOptiSetupData', 'SaveFields:=',  ...
false, 'CopyMesh:=', false}, {'NAME:StartingPoint'}, 'Sim. Setups:=', ...
{'Setup1'}, {'NAME:Sweeps', ...
{'NAME:SweepDefinition', 'Variable:=', 'Idc', 'Data:=', ...
'LINC 0.1A 1A 10', 'OffsetF1:=', false, 'Synchronize:=', 0}}, ...
{'NAME:Sweep Operations'}, {'NAME:Goals', {'NAME:Goal', 'ReportType:=', ...
'Magnetostatic', 'Solution:=', 'Setup1 : LastAdaptive', ...
{'NAME:SimValueContext'}, 'Calculation:=', ...
'Matrix1.MagFlux(Current1)', {'NAME:Ranges'}}}})

Module = Design.GetModule('OutputVariable')

invoke(Module,'CreateOutputVariable', 'Flux', 'Matrix1.MagFlux(Current1)', ...
'Setup1 : LastAdaptive', 'Magnetostatic', {})

invoke(Project,'AnalyzeAll')

Module = Design.GetModule('ReportSetup')

invoke(Module,'CreateReport', 'XY Plot 1', 'Magnetostatic', 'XY Plot',  ...
'Setup1 : LastAdaptive', {}, {'Idc:=', {'All'}, 'H1:=', { ...
'Nominal'}, 'H2:=', {'Nominal'}, 'D2:=', {'Nominal'}, 'extra:=', { ...
'Nominal'}, 'ratio:=', {'Nominal'}, 'N:=', {'Nominal'}, 'D1:=', { ...
'Nominal'}}, {'X Component:=', 'Idc', 'Y Component:=', {'Flux'}}, {})

for i=1:10
current(i)=i*0.1
end

Module = Design.GetModule('OutputVariable')

Val= Module.GetOutputVariableValue('flux','Idc=0.1A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(1)=Val

Val= Module.GetOutputVariableValue('flux','Idc=0.2A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(2)=Val

Val= Module.GetOutputVariableValue('flux','Idc=0.3A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(3)=Val

Val= Module.GetOutputVariableValue('flux','Idc=0.4A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(4)=Val

Val= Module.GetOutputVariableValue('flux','Idc=0.5A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(5)=Val

Val= Module.GetOutputVariableValue('flux','Idc=0.6A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(6)=Val

Val= Module.GetOutputVariableValue('flux','Idc=0.7A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(7)=Val

Val= Module.GetOutputVariableValue('flux','Idc=0.8A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(8)=Val

Val= Module.GetOutputVariableValue('flux','Idc=0.9A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(9)=Val

Val= Module.GetOutputVariableValue('flux','Idc=1A', ...
'Setup1 : LastAdaptive', 'Magnetostatic', '')
flux(10)=Val

plot(current,flux)

delete(iMaxwell)
